config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :articles

  root to: "articles#index"

  # #index
  # get "articles", to: "articles#index"
  # #new
  # get "articles/new", to: "articles#new"
  # #create
  # post "articles", to: "articles#create", as: :new_article
  # #edit
  # get "articles/:id/edit", to: "articles#edit", as: :edit_article
  # #update
  # patch "articles/:id", to: "articles#update"
  # #show
  # get "articles/:id", to: "articles#show", as: :article
  # #destroy
  # delete "articles/:id", to: "articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @link = "https://en.wikipedia.org/wiki/#{@article.title}"
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h2> Editing Article: <%= @article.title %></h2>

<p> <%= @article.content %> </p>

<%= form_with model: @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to Index", articles_path %>

app/views/articles/index.html.erb
<h2> Articles </h2>

<div class = "btn">
<button class="btn btn-primary text-decoration-none">
<%= link_to "New Article", new_article_path, class: "no-blue"%>
</button>
</div>

<ul>
  <% @articles.each do |article| %>
    <li> <%= link_to article.title, article_path(article) %> </li>
    <p> <%= article.content %> </p>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h2> New Article </h2>

<%= form_with article: @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to Index", articles_path %>

app/views/articles/show.html.erb
<h2> <%= @article.title %> </h2>



<p> <%= link_to "Wikipedia", @link %> </p>

<p> <%= @article.content %> </p>

<button class="btn btn-primary text-decoration-none">
<%= link_to "Edit Article", edit_article_path(@article), class: "no-blue" %>
</button>

<button class="btn btn-primary text-decoration-none">
<%= link_to "Delete Article", article_path(@article), class: "no-blue",
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</button>

<p> <%= link_to "Return to Index", articles_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>

  <body>
    <div class="banner">
      <h1> <%= link_to "Wackypedia", articles_path, style: "text-decoration: none; color: black;" %> </h1>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>